apiVersion: v1
data:
  mongod.conf: |
    {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.5.5
    heritage: Tiller
    release: my-release
  name: my-release-mongodb-replicaset-mongodb
  selfLink: /api/v1/namespaces/default/configmaps/my-release-mongodb-replicaset-mongodb
